// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evmamwdmwogmlezndueg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bWFtd2Rtd29nbWxlem5kdWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTQ1NjcsImV4cCI6MjA2NTUzMDU2N30.c5UTSaA5p9-7cD4HnizalfZUHjFZijmSpuET98YgTA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);